name: habar
description: Mobile client for habr.com
publish_to: "none"
version: 1.10.0+25

environment:
  #  sdk: ">=2.18.0 <3.0.0"
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  rxdart: ^0.27.7
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.2.2
  share: ^2.0.4
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  get: ^4.6.6
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.4
  flutter_svg: ^2.0.9
  filesystem_picker: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
