name: habar
description: Mobile client for habr.com
publish_to: "none"
version: 1.5.2+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  rxdart: ^0.27.2
  flutter_html: ^2.1.5
  url_launcher: ^6.0.15
  share: ^2.0.4
  intl: ^0.17.0
  cached_network_image: ^3.1.0+1
  get: ^4.3.8
  image_gallery_saver: ^1.7.1
  permission_handler: ^8.3.0
  path: ^1.8.0
  path_provider: ^2.0.7
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_advanced_segment: ^2.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
