name: habar
description: Mobile client for habr.com
publish_to: "none" 
version: 1.1.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  rxdart: ^0.27.1
  flutter_html: ^2.1.0
  url_launcher: ^6.0.3
  share: ^2.0.4
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
